version: "3.9"

services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - "9023:9023"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DUTU_DB_HOSTNAME=db
      - DUTU_DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "7432:5432"
    volumes:
      - dutu_db:/var/lib/postgresql/data

volumes:
    dutu_db:
